// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqwssugwrqatkksihpvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxd3NzdWd3cnFhdGtrc2locHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwOTAxNzUsImV4cCI6MjA0OTY2NjE3NX0.QZzRpEYGV71Ln33tls0iQ-_V1rOhd_oCKdXiS7VPEGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);